CREATE TABLE IF NOT EXISTS player_season_statistics (
    player_id BIGINT NOT NULL REFERENCES player(id),
    unique_tournament_id BIGINT NOT NULL REFERENCES unique_tournament(id),
    season_id BIGINT NOT NULL REFERENCES season(id),
    team_id BIGINT NOT NULL REFERENCES team(id),
    stat_type TEXT NOT NULL,
    statistics_id BIGINT,
    season_year TEXT,
    start_year INTEGER,
    end_year INTEGER,
    accurate_crosses INTEGER,
    accurate_crosses_percentage NUMERIC,
    accurate_long_balls INTEGER,
    accurate_long_balls_percentage NUMERIC,
    accurate_passes INTEGER,
    accurate_passes_percentage NUMERIC,
    aerial_duels_won INTEGER,
    appearances INTEGER,
    assists INTEGER,
    big_chances_created INTEGER,
    big_chances_missed INTEGER,
    blocked_shots INTEGER,
    clean_sheet INTEGER,
    count_rating INTEGER,
    dribbled_past INTEGER,
    error_lead_to_goal INTEGER,
    expected_assists NUMERIC,
    expected_goals NUMERIC,
    goals INTEGER,
    goals_assists_sum INTEGER,
    goals_conceded INTEGER,
    goals_prevented NUMERIC,
    interceptions INTEGER,
    key_passes INTEGER,
    minutes_played INTEGER,
    outfielder_blocks INTEGER,
    pass_to_assist INTEGER,
    rating NUMERIC,
    red_cards INTEGER,
    saves INTEGER,
    shots_from_inside_the_box INTEGER,
    shots_on_target INTEGER,
    successful_dribbles INTEGER,
    tackles INTEGER,
    total_cross INTEGER,
    total_long_balls INTEGER,
    total_passes INTEGER,
    total_rating NUMERIC,
    total_shots INTEGER,
    yellow_cards INTEGER,
    statistics_payload JSONB,
    PRIMARY KEY (player_id, unique_tournament_id, season_id, team_id, stat_type)
);

CREATE INDEX IF NOT EXISTS idx_player_season_statistics_player
    ON player_season_statistics(player_id);

CREATE INDEX IF NOT EXISTS idx_player_season_statistics_ut_season
    ON player_season_statistics(unique_tournament_id, season_id);
