"""SportradarCoverageGate — endpoint pre-filter using Sportradar coverage matrix.

Evaluates whether a fetch task should proceed based on the per-attribute
Sportradar coverage profile of the target competition. Phase 1 scope:
**football only**, 11 hard-gate path_templates + 1 dry-run-observation
endpoint.

Decision tree (priority order, top check wins):

    1. kill_switch disabled               → allow
    2. ctx.has_full_context == False      → allow + log
    3. ctx.sport_slug != "football"       → allow
    4. ctx.is_editor == True              → allow
    5. path not in mapping                → allow
    6. attr in BYPASS_ATTRS                → allow + log
    7. path in DRYRUN_ONLY_ENDPOINTS       → continue, force dry-run
    8. ut_id missing in coverage table    → allow
    9. confidence < MIN_CONFIDENCE        → allow
   10. attr value NULL                    → allow
   11. attr value >= min_value            → allow
   12. global DRY_RUN OR forced (step 7)  → allow + log
   13. else                               → BLOCK

The mapping ``ENDPOINT_TO_COVERAGE_REQUIREMENT`` is **derived from**
``tools/sportradar_openapi_audit.py`` v2 (validated against Sportradar
OpenAPI spec). When SR adds new endpoints or we discover Sofascore paths,
re-run the audit and update this dict.

See ``docs/superpowers/plans/2026-05-08-p3-2-sportradar-coverage-gate.md``.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from typing import Any, Mapping, Protocol

from .gate_context_resolver import GateContext

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Endpoint → required Sportradar coverage attribute mapping.
#
# Generated by tools/sportradar_openapi_audit.py v2 (Section 4 dict).
# Strictly registry-driven, single source of truth.
# Endpoint NOT in this dict → fail open.
# ---------------------------------------------------------------------------

ENDPOINT_TO_COVERAGE_REQUIREMENT: dict[str, tuple[str, int]] = {
    # Event-level (4)
    "/api/v1/event/{event_id}/h2h": ("Head2Head", 1),
    "/api/v1/event/{event_id}/incidents": ("Basic Play by Play", 1),
    "/api/v1/event/{event_id}/lineups": ("Lineups", 1),
    "/api/v1/event/{event_id}/statistics": ("Basic Statistics", 1),
    # Season-level Leaders endpoints (7)
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/player-of-the-season":
        ("Leaders", 1),
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-players-per-game/all/overall":
        ("Leaders", 1),
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-players-per-game/all/regularSeason":
        ("Leaders", 1),
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-players/overall":
        ("Leaders", 1),
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-players/regularSeason":
        ("Leaders", 1),
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-teams/overall":
        ("Leaders", 1),
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-teams/regularSeason":
        ("Leaders", 1),
    # Dry-run observation only (1) — included so resolver/gate evaluate it,
    # actual block is suppressed by DEFAULT_DRYRUN_ONLY_ENDPOINTS below
    # until Phase 5 graduation.
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-ratings/overall":
        ("Leaders", 1),
}

# Sport scope: Phase 1 = football only.
DEFAULT_SPORT_SCOPE: frozenset[str] = frozenset({"football"})

# Endpoints kept in dry-run mode regardless of global DRY_RUN setting until
# manual graduation review (T+30 days, Phase 5).
DEFAULT_DRYRUN_ONLY_ENDPOINTS: frozenset[str] = frozenset({
    "/api/v1/unique-tournament/{unique_tournament_id}/season/{season_id}/top-ratings/overall",
})


# ---------------------------------------------------------------------------
# Gate decision dataclass + result enum.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class GateDecision:
    """Outcome of a single gate evaluation.

    ``allow`` = should_fetch True. ``block`` = should_fetch False.
    ``logged_event`` carries telemetry payload for structured logging.
    """

    allow: bool
    reason: str
    logged_event: Mapping[str, Any] | None = None

    @property
    def should_fetch(self) -> bool:
        return self.allow


# ---------------------------------------------------------------------------
# Coverage row protocol — matches asyncpg Record subset.
# ---------------------------------------------------------------------------

class _CoverageLookup(Protocol):
    """Minimal interface for coverage lookups.

    Real implementation in ``schema_inspector.storage.sportradar_repository``
    (TBD). For tests, an in-memory dict-based fake is enough.
    """

    async def fetch_for_ut(self, unique_tournament_id: int) -> Mapping[str, Any] | None: ...


# ---------------------------------------------------------------------------
# The gate.
# ---------------------------------------------------------------------------

class SportradarCoverageGate:
    """Per-attribute coverage gate for Sofascore fetch tasks.

    Stateless evaluator — all configuration is captured at construction time.
    Safe to call concurrently from many tasks; the underlying coverage lookup
    is responsible for its own concurrency.

    Args:
        coverage_lookup: object with ``fetch_for_ut(ut_id) -> Mapping`` async method.
        endpoint_to_coverage: optional override for endpoint → (attr, min) map.
            Defaults to module-level ``ENDPOINT_TO_COVERAGE_REQUIREMENT``.
        sport_scope: set of allowed sport slugs. Defaults to football-only.
        dryrun_only_endpoints: set of path_templates kept in dry-run regardless
            of global DRY_RUN setting.
        env: env-var dict for testability (defaults to os.environ).
    """

    ENV_ENABLED = "SCHEMA_INSPECTOR_SPORTRADAR_GATE_ENABLED"
    ENV_DRY_RUN = "SCHEMA_INSPECTOR_SPORTRADAR_GATE_DRY_RUN"
    ENV_MIN_CONFIDENCE = "SCHEMA_INSPECTOR_SPORTRADAR_GATE_MIN_CONFIDENCE"
    ENV_BYPASS_ATTRS = "SCHEMA_INSPECTOR_SPORTRADAR_GATE_BYPASS_ATTRS"
    ENV_BYPASS_SPORTS = "SCHEMA_INSPECTOR_SPORTRADAR_GATE_BYPASS_SPORTS"
    ENV_DRYRUN_ONLY_ENDPOINTS = "SCHEMA_INSPECTOR_SPORTRADAR_GATE_DRYRUN_ONLY_ENDPOINTS"

    def __init__(
        self,
        *,
        coverage_lookup: _CoverageLookup,
        endpoint_to_coverage: Mapping[str, tuple[str, int]] | None = None,
        sport_scope: frozenset[str] = DEFAULT_SPORT_SCOPE,
        dryrun_only_endpoints: frozenset[str] = DEFAULT_DRYRUN_ONLY_ENDPOINTS,
        env: Mapping[str, str] | None = None,
    ) -> None:
        self._coverage_lookup = coverage_lookup
        self._endpoint_to_coverage = (
            dict(endpoint_to_coverage)
            if endpoint_to_coverage is not None
            else dict(ENDPOINT_TO_COVERAGE_REQUIREMENT)
        )
        self._sport_scope = sport_scope
        self._env = env if env is not None else os.environ
        self._dryrun_only_endpoints = self._merge_endpoint_set(
            base=dryrun_only_endpoints,
            env_value=self._env.get(self.ENV_DRYRUN_ONLY_ENDPOINTS, ""),
        )

    # -------------- public API --------------

    async def should_fetch(
        self,
        *,
        path_template: str,
        ctx: GateContext,
    ) -> GateDecision:
        """Decide whether to fetch ``path_template`` for the given context.

        Returns :class:`GateDecision`. Caller must:
          - on ``allow=True``: proceed with fetch.
          - on ``allow=False``: skip fetch, ack/mark job as
            ``succeeded_skipped_by_gate``.
          - on ``logged_event != None``: emit structured log line for
            telemetry / dry-run analysis.
        """
        # 1. Kill-switch
        if not self._is_enabled():
            return GateDecision(allow=True, reason="gate_disabled")

        # 2. Missing context
        if not ctx.has_full_context:
            return GateDecision(
                allow=True,
                reason="missing_context",
                logged_event={
                    "event": "sportradar_gate_missing_context",
                    "path_template": path_template,
                    "missing_reason": ctx.missing_reason,
                },
            )

        # 3. Sport scope
        if ctx.sport_slug not in self._sport_scope and not self._sport_in_bypass(ctx.sport_slug):
            return GateDecision(allow=True, reason="sport_out_of_scope")

        # 4. is_editor → Sofascore-sourced data, gate doesn't apply
        if ctx.is_editor:
            return GateDecision(allow=True, reason="is_editor_true")

        # 5. Endpoint not mapped → no rule, allow
        rule = self._endpoint_to_coverage.get(path_template)
        if rule is None:
            return GateDecision(allow=True, reason="path_template_not_mapped")
        required_attr, min_value = rule

        # 6. BYPASS_ATTRS short-circuit (BEFORE DB lookup)
        bypass_attrs = self._bypass_attrs_set()
        if required_attr in bypass_attrs:
            return GateDecision(
                allow=True,
                reason=f"bypass_attr:{required_attr}",
                logged_event={
                    "event": "sportradar_gate_bypass_attr",
                    "path_template": path_template,
                    "ut_id": ctx.unique_tournament_id,
                    "attr": required_attr,
                },
            )

        # 7. DRYRUN_OBSERVATION_ONLY policy → continue evaluation but force dry-run
        force_dry_run = path_template in self._dryrun_only_endpoints

        # 8. Coverage row lookup
        if ctx.unique_tournament_id is None:
            return GateDecision(allow=True, reason="no_ut_id")
        try:
            row = await self._coverage_lookup.fetch_for_ut(int(ctx.unique_tournament_id))
        except Exception as exc:
            logger.warning(
                "SportradarCoverageGate coverage lookup failed: ut_id=%s err=%s",
                ctx.unique_tournament_id, exc,
            )
            return GateDecision(allow=True, reason="lookup_error")
        if row is None:
            return GateDecision(allow=True, reason="coverage_missing")

        # 9. Reconciliation confidence
        confidence = float(row.get("reconciliation_confidence") or 0)
        min_conf = self._min_confidence()
        if confidence < min_conf:
            return GateDecision(allow=True, reason=f"low_confidence:{confidence:.2f}")

        # 10. Attribute value
        coverage_attrs = row.get("coverage_attrs") or {}
        if not isinstance(coverage_attrs, Mapping):
            return GateDecision(allow=True, reason="coverage_attrs_not_mapping")
        coverage_value = coverage_attrs.get(required_attr)
        if coverage_value is None:
            return GateDecision(allow=True, reason="attr_value_null")

        try:
            cv = int(coverage_value)
        except (TypeError, ValueError):
            return GateDecision(allow=True, reason="attr_value_not_int")

        # 11. Coverage adequate
        if cv >= min_value:
            return GateDecision(allow=True, reason="coverage_adequate")

        # 12. Block path: dry-run check
        global_dry_run = self._is_dry_run()
        if global_dry_run or force_dry_run:
            return GateDecision(
                allow=True,
                reason="dry_run_would_block",
                logged_event={
                    "event": "sportradar_gate_dryrun",
                    "would_block": True,
                    "path_template": path_template,
                    "event_id": ctx.event_id,
                    "ut_id": ctx.unique_tournament_id,
                    "sport_slug": ctx.sport_slug,
                    "is_editor": ctx.is_editor,
                    "required_attr": required_attr,
                    "coverage_value": cv,
                    "min_value": min_value,
                    "reconciliation_confidence": confidence,
                    "force_dry_run": force_dry_run,
                },
            )

        # 13. BLOCK
        return GateDecision(
            allow=False,
            reason="coverage_insufficient",
            logged_event={
                "event": "sportradar_gate_block",
                "path_template": path_template,
                "event_id": ctx.event_id,
                "ut_id": ctx.unique_tournament_id,
                "sport_slug": ctx.sport_slug,
                "required_attr": required_attr,
                "coverage_value": cv,
                "min_value": min_value,
                "reconciliation_confidence": confidence,
            },
        )

    # -------------- env helpers --------------

    def _is_enabled(self) -> bool:
        return _env_bool(self._env, self.ENV_ENABLED, default=False)

    def _is_dry_run(self) -> bool:
        return _env_bool(self._env, self.ENV_DRY_RUN, default=True)

    def _min_confidence(self) -> float:
        raw = self._env.get(self.ENV_MIN_CONFIDENCE)
        if not raw:
            return 0.9
        try:
            value = float(raw)
        except ValueError:
            return 0.9
        if value < 0.0:
            return 0.0
        if value > 1.0:
            return 1.0
        return value

    def _bypass_attrs_set(self) -> frozenset[str]:
        raw = self._env.get(self.ENV_BYPASS_ATTRS, "")
        if not raw:
            return frozenset()
        return frozenset(s.strip() for s in raw.split(",") if s.strip())

    def _sport_in_bypass(self, sport_slug: str | None) -> bool:
        if not sport_slug:
            return False
        raw = self._env.get(self.ENV_BYPASS_SPORTS, "")
        if not raw:
            return False
        return sport_slug in {s.strip() for s in raw.split(",") if s.strip()}

    @staticmethod
    def _merge_endpoint_set(*, base: frozenset[str], env_value: str) -> frozenset[str]:
        """Merge default DRYRUN_ONLY_ENDPOINTS with optional env override.

        Env value REPLACES default when set (CSV of full path_templates).
        Env empty → use default.
        """
        if not env_value.strip():
            return base
        return frozenset(s.strip() for s in env_value.split(",") if s.strip())


def _env_bool(env: Mapping[str, str], name: str, *, default: bool) -> bool:
    raw = env.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


__all__ = [
    "DEFAULT_DRYRUN_ONLY_ENDPOINTS",
    "DEFAULT_SPORT_SCOPE",
    "ENDPOINT_TO_COVERAGE_REQUIREMENT",
    "GateDecision",
    "SportradarCoverageGate",
]
