"""Canonical job type identifiers for the hybrid ETL planner."""

JOB_DISCOVER_SPORT_SURFACE = "discover_sport_surface"
JOB_EXPAND_CATEGORY = "expand_category"
JOB_SYNC_UNIQUE_TOURNAMENT = "sync_unique_tournament"
JOB_SYNC_SEASON_INDEX = "sync_season_index"
JOB_SYNC_SEASON_SURFACE = "sync_season_surface"
JOB_SYNC_SEASON_WIDGET = "sync_season_widget"
JOB_DISCOVER_TOURNAMENT_EVENTS = "discover_tournament_events"
JOB_DISCOVER_EVENT_SURFACE = "discover_event_surface"
JOB_HYDRATE_EVENT_ROOT = "hydrate_event_root"
JOB_HYDRATE_EVENT_EDGE = "hydrate_event_edge"
JOB_HYDRATE_ENTITY_PROFILE = "hydrate_entity_profile"
JOB_HYDRATE_ENTITY_SEASON = "hydrate_entity_season"
JOB_HYDRATE_SPECIAL_ROUTE = "hydrate_special_route"
JOB_TRACK_LIVE_EVENT = "track_live_event"
JOB_REFRESH_LIVE_EVENT = "refresh_live_event"
JOB_FINALIZE_EVENT = "finalize_event"
JOB_NORMALIZE_SNAPSHOT = "normalize_snapshot"
JOB_RECONCILE_CAPABILITY = "reconcile_capability"
JOB_REPLAY_FAILED_JOB = "replay_failed_job"
